 # # # # # # # # # # # # # # # # # # # # # # # #
# REPLACE THE FOLLOWING VARIABLES AND ADJUST 
# - ENVIRONMENT_REFERENCE
# - CLIENT_ID_SECRET_REFERENCE
# - SUBSCRIPTION_ID_SECRET_REFERENCE
# - TENANT_ID_SECRET_REFERENCE
# - RESOURCE_GROUP_REFERENCE
# - STORAGE_ACCOUNT_REFERENCE
# - CONTAINER_NAME_REFERENCE
#
# # # # # # # # # # # # # # # # # # # # # # # # #

name: Deploy Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_job:
    runs-on: ubuntu-latest
    environment: ENVIRONMENT_REFERENCE #Should be changed, lol
    defaults:
      run:
        working-directory: ./Terraform
    
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID_SECRET_REFERENCE }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID_SECRET_REFERENCE }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID_SECRET_REFERENCE }}"
      ARM_USE_AZUREAD: true

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.RESOURCE_GROUP_REFERENCE }}" \
        -backend-config=storage_account_name="${{ secrets.STORAGE_ACCOUNT_REFERENCE }}" \
        -backend-config=container_name="${{ secrets.CONTAINER_NAME_REFERENCE }}" \
        -backend-config=key="KEY_NAME"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file="envs/dev/vars.dev.tfvars" -out=tfplan #UPDATE VARS file

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan